Algoritmo "Matriz - 3x2"


Var

   mat: vetor[1..3, 1..2] de Inteiro
   l, c: Inteiro

Inicio

   Para l <- 1 ate 3 faca
      Para c <- 1 ate 2 faca
         Escreva ("Digite um valor para [ ", l," , ",c," ]:" )
         Leia(mat[l,c])
      FimPara
   FimPara

   Para l <- 1 ate 3 faca
      Para c <- 1 ate 2 faca
         Escreva (mat[l,c]:4)
      FimPara
      Escreval()
   FimPara

Fimalgoritmo