Algoritmo "Procedimento com Referência e Paramêtros - Somando Valores"


Var

   X, Y: Inteiro

Procedimento Soma (var A,B : Inteiro)

Inicio

   A <- A + 1
   B <- B + 2
   Escreval("O valor de A é ",A)
   Escreval("O valor de B é ",B)
   Escreval("A soma de A + B é", A+B)

FimProcedimento

Inicio

   X <- 2
   Y <- 6
   Soma (X, Y)
   Escreval("O valor de X é ", X)
   Escreval("O valor de Y é ", Y)

Fimalgoritmo